customhost = "cc-asmdb.czvrowtwhg9s.us-east-1.rds.amazonaws.com"
customuser = "admin"
custompass = "12345678"
customdb = "employee"
custombucket = "jeremy-david-jaedon-bucket"
customregion = "us-east-1"
